-development:
  forest_env_secret: c36c8dc7dcbf9984414d51f84cd7fa862d807c4bebcf28d9a635cb9680f6abc3
  forest_auth_secret: obXUeO1X8_ircc3yW-8dkg
  forest_application_url: http://localhost:3000
-staging:
  forest_env_secret: <%= ENV["FOREST_ENV_SECRET"] %>
  forest_auth_secret: <%= ENV["FOREST_AUTH_SECRET"] %>
  forest_application_url: <%= ENV["FOREST_APPLICATION_URL"] %>
-production:
  forest_env_secret: <%= ENV["FOREST_ENV_SECRET"] %>
  forest_auth_secret: <%= ENV["FOREST_AUTH_SECRET"] %>
  forest_application_url: <%= ENV["FOREST_APPLICATION_URL"] %>